title: Holland's Blog
# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /blog
description: The intersection of leadership, software engineering, and life
domain: blog.hollandgibson.com
lang: en
plugins:
  - jekyll-seo-tag
  - jekyll-feed
exclude:
  - LICENSE
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - assets_orig
  - bin
  - _sass
header_pages:
  - about.asciidoc
minima:
  skin: classic
keep_files:
  - assets/images
feed:
  title: Holland Gibson's blog
  url: https://blog.hollandgibson.com
collections:
  family:
    output: true
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    imagesdir: /assets/images
    # iconsdir: '{imagesdir}/icons'
    idseparator: _
    stylesdir: /_sass
    source-highlighter: pygments
    pygments-css: class
    pygments-style: "monokai"
