title: Jekyll AsciiDoc Quickstart
# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /blog
description: The intersection of military doctrine, software engineering, and life
exclude:
- LICENSE
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile
- assets_orig
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: coderay
