= About
:page-layout: page
:page-permalink: /about/

My public-keys:

[cols="1,1"]
|===
| For routine things
| `ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBillLJ5wk4c/gN6NLQjypX/5jOL091Cd708K7WLUHIpqq6STP5A63TwWqay7LnGABpcJJFOGtodFo8kWa3xs6w=`

| For more sensitive things
| `ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBK4bhROJKj8Td4hDsKn7zVZmCVkYFJX5YkTDLVRlmEop795/y0dk16JbjzvD+7p3l0GGc3vTUB6vHvzdzrrF5gI=`
|===

I write this blog to organize my thoughts and while I hope that someone finds them useful, I am content with them only having 1 reader - me, but if you want to read it that would be swell 😁.

I am a soldier (6 years in the US Army, although I got out a handful of years ago), a father, a man with too many interests, and a software engineer.
I've been an infantry officer, DevOps engineer, Tech Lead, ML Engineer, and backend engineer.
The thing I like most (besides my lovely wife) is building things with software.
The thing I find most fulfilling (professionally) getting difficult people to work as a part of a team.

I'm not really sure where this blog will go, if anywhere, so please let me know if you have comments: author (at) blog.hollandgibson.com
