version: 2.1

jobs:
  asciidoctor:
    docker:
      - image: "asciidoctor/docker-asciidoctor:1.69"
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    environment:
      HTML_DIR: "/tmp/htmlposts"
    steps:
      - checkout
      - run:
          name: "Make output dir"
          command: "mkdir -p /tmp/htmlposts"
      - run:
          name: "Compile _posts to html"
          command: "./bin/ci_asciidoctor_html.sh"
      - persist_to_workspace: 
          root: "/tmp/htmlposts"
          paths: 
            - "*.html"
  aspell:
    docker:
      - image: "hgibs/aspell:latest"
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    environment:
      HTML_DIR: "/tmp/htmlposts"
    steps:
      - checkout
      - attach_workspace:
          at: "/tmp/htmlposts"
      - run:
          name: "Check spelling on html-formatted posts"
          command: "./bin/ci_verify_spelling.sh"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - asciidoctor
      - aspell:
          requires:
            - asciidoctor
      
