= How to be a parent (or loved one) in the hospital
:page-navtitle: parent in the hospital
:page-excerpt: There is a lot to do when you aren't in charge
:toc:


You would think that being the patient (or acting on their behalf) in a hospital would mean having lots of people take care of you.
In my experience, this is only part of the deal.

Having spent close to 90 days (and most of those nights) in the hospital as a healthy parent of a sick child over the last year or so, I've started jotting down reminders on all the things I should be doing.

I hope this post helps anyone who finds themselves or is with someone in the hospital and helps you get the best treatment possible.


== Things the providers don't do
* coordinate with other teams
* check for new notes after rounds
* think very hard about patient-comfort


=== Not coordinating with other teams
I had naively assumed that the providers and professionals in the pediatric ICU would be a well-oiled machine that worked hand-in-hand with their counterparts: the cardialogy team talked to the nephrology team, and the charge nurse knew both of their updates.

I think that the providers (doctors, nurse practioners, nurses, therapists, etc) each work on finding solutions to things that they are uniquely educated to do.
Of course there is a lot of overlap in their expertise. As an example: despite it being something the nurses do more often, just about any provider can (and will) adjust the air flow to the 
link:[https://en.wikipedia.org/wiki/Nasal_cannula[nasal canula]]
as needed. 

It ...

=== Checking for new notes after rounds
Generally, the providers review notes prior-to rounds, during rounds, and when they are expecting something (like the results of the ultrasound they ordered).

...